pipeline:
    build:
        image: alpine:3.9
        pull: true

    s3:
        image: plugins/s3
        bucket: boops.org
        source: public/*
        strip_prefix: public/
        secrets: [aws_access_key_id, aws_secret_access_key]
