# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sir. Bøøps
# email: your-email@domain.com
description: Just a blog for a bored internet user.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boops.me" # the base hostname & protocol for your site
twitter_username: Sir_Boops
github_username:  Sir-Boops

# Build settings
markdown: kramdown
